#!/bin/sh

set -euo pipefail

IFS=$'\n\t'

[ $# -lt 1 ] && echo ">>> ERROR: Custom initramfs script must be supplied an argument (kernel version)!" && exit 99

VERSION="$1"
ROOTDEV="/dev/nvme0n1p2"
INITSRC="/etc/kernel/init.script"
INFILES=(
    "/bin/busybox"
    "/sbin/cryptsetup"
    "/data/bin/gamma"
)
OUTFILE="/boot/initramfs-${VERSION}.img"

create_initramfs() {
    local quit=0
    local lib64="/lib64"
    local rootdir="$(mktemp -d)"

    echo ">>> Building initramfs for kernel $VERSION in $rootdir..."

    # Check that the source init file exists on the system.
    [ ! -f "$INITSRC" ] && echo ">>> ERROR: File missing (init): $INITSRC" && quit=1

    # Check that all required binaries exist on the system.
    for bin in ${INFILES[@]}; do
        [ ! -f "$bin" ] && echo ">>> ERROR: File missing (binary): $bin" && quit=2
    done

    # Terminate early if prerequisites are not met.
    [ "$quit" -eq 1 ] && echo ">>> ERROR: Aborting because init file was missing!" && exit 1
    [ "$quit" -eq 2 ] && echo ">>> ERROR: Aborting because one or more binary files were missing!" && exit 2

    # Create the root filesystem structure.
    mkdir -p "$rootdir"/{dev,etc,mnt,proc,run,sys,usr/bin,usr/sbin,usr/lib64}

    # Create merged-usr symlinks.
    (cd "$rootdir" && ln -s usr/bin && ln -s usr/sbin && ln -s usr/lib64)

    # Create a temporary file to buffer library file paths.
    libfile="$(mktemp)"

    # Scrape dynamic libraries.
    for bin in ${INFILES[@]}; do
        # Copy the binary directly.
        cp "$(realpath "$bin")" "$rootdir/bin/"
        # Collect the dependency libraries.
        for lib in $(ldd "$bin" | grep -o '/[^ ]*'); do
            # Collect the library file or link without dereferencing.
            echo "$lib" >> $libfile
            local cur="$lib"
            while [ -L "$cur" ]; do
                local tgt=$(readlink -f "$cur")
                echo "$tgt" >> $libfile
                cur="$tgt"
            done
        done
    done

    # Copy over the collected library files.
    for path in $(cat $libfile | sort -u); do
        cp --parents -P "$path" "$rootdir/"
    done

    # Inject UUID of the LUKS partition.
    UUID=$(blkid -s UUID -o value "$ROOTDEV")
    cat "$INITSRC" | sed "s/SLOT_FOR_CRYPT_UUID/$UUID/" > "$rootdir/init"
    chmod +x "$rootdir/init"

    # Verify linker setup
    echo ">>> Verifying dynamic linker setup..."
    if ! chroot "$rootdir" /bin/busybox sh -c "exit 0"; then
        echo ">>> ERROR: Aborting because symlink structure is broken!"
        exit 3
    fi

    cd "$rootdir"
    echo ">>> Creating final output at $OUTFILE..."
    (
        find . -print0 | { cpio --null -o --format=newc 2>&1 >&3 | (grep -v "blocks$" || true) >&2; } 3>&1 | zstd -19 -T0 > "$OUTFILE"
    )
    echo ">>> SUCCESS!"
}

create_initramfs
